package com.pathpedi.app

import android.annotation.SuppressLint
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.webkit.JavascriptInterface
import android.webkit.WebChromeClient
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import java.io.File
import java.io.FileOutputStream

class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        webView = WebView(this)

        webView.settings.apply {
            javaScriptEnabled = true
            domStorageEnabled = true
            databaseEnabled = true
            allowFileAccess = true
            allowContentAccess = true
            javaScriptCanOpenWindowsAutomatically = true
            cacheMode = WebSettings.LOAD_DEFAULT
        }

        webView.addJavascriptInterface(
            PrintBridge(this),
            "AndroidPrint"
        )

        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                super.onPageFinished(view, url)

                view?.evaluateJavascript(
                    """
                    (function() {
                        window.print = function() {
                            if (window.AndroidPrint && AndroidPrint.print) {
                                AndroidPrint.print();
                            }
                        };
                    })();
                    """.trimIndent(),
                    null
                )
            }
        }

        webView.webChromeClient = WebChromeClient()
        setContentView(webView)

        webView.loadUrl("file:///android_asset/Pathpedi.html")

        onBackPressedDispatcher.addCallback(
    this,
    object : OnBackPressedCallback(true) {
        override fun handleOnBackPressed() {
            if (webView.canGoBack()) {
                webView.goBack()
            } else {
                finish()
            }
        }
    }
)
    }

    override fun onResume() {
        super.onResume()
        if (::webView.isInitialized) {
            webView.visibility = WebView.VISIBLE
            webView.postDelayed({
                if (!isFinishing && !isDestroyed) {
                    webView.requestFocus()
                }
            }, 200)
        }
    }

    private class PrintBridge(
        private val context: Context
    ) {

        @JavascriptInterface
        fun print() {
            val activity = context as? MainActivity ?: return
            activity.runOnUiThread {
                activity.webView.evaluateJavascript(
                    "(function(){return document.documentElement.outerHTML;})()"
                ) { htmlResult ->
                    try {
                        val html = decodeJsString(htmlResult)
                        val file = File(
                            activity.cacheDir,
                            "pathpedi_print_preview.html"
                        )
                        file.writeText(html, Charsets.UTF_8)

                        val intent = Intent(
                            activity,
                            PrintPreviewActivity::class.java
                        )
                        intent.putExtra("HTML_FILE", file.absolutePath)
                        activity.startActivity(intent)
                    } catch (e: Exception) {
                        e.printStackTrace()
                    }
                }
            }
        }

        @JavascriptInterface
        fun printHtml(html: String) {
            val activity = context as? MainActivity ?: return
            activity.runOnUiThread {
                try {
                    val file = File(
                        activity.cacheDir,
                        "pathpedi_daybook_print.html"
                    )
                    file.writeText(html, Charsets.UTF_8)

                    val intent = Intent(
                        activity,
                        PrintPreviewActivity::class.java
                    )
                    intent.putExtra("HTML_FILE", file.absolutePath)
                    activity.startActivity(intent)
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }

        /**
         * Save CSV generated by Pathpedi HTML into the public
         * Downloads/Pathpedi folder on Android 10+.
         */
        @JavascriptInterface
fun saveCSV(filename: String, base64Data: String): Boolean {

    val activity = context as? MainActivity ?: return false

    return try {

        val safeName = filename
            .replace("/", "_")
            .replace("\\", "_")
            .ifBlank { "pathpedi_export.csv" }

        val bytes = Base64.decode(
            base64Data,
            Base64.DEFAULT
        )

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {

            val values = ContentValues().apply {

                put(
                    MediaStore.Downloads.DISPLAY_NAME,
                    safeName
                )

                put(
                    MediaStore.Downloads.MIME_TYPE,
                    "text/csv"
                )

                put(
                    MediaStore.Downloads.RELATIVE_PATH,
                    Environment.DIRECTORY_DOWNLOADS + "/Pathpedi/"
                )

                put(
                    MediaStore.Downloads.IS_PENDING,
                    1
                )
            }

            val resolver = activity.contentResolver

            val uri = resolver.insert(
                MediaStore.Downloads.EXTERNAL_CONTENT_URI,
                values
            ) ?: throw Exception(
                "MediaStore insert failed"
            )

            try {

                resolver.openOutputStream(uri)?.use { output ->

                    output.write(bytes)
                    output.flush()

                } ?: throw Exception(
                    "Could not open CSV output stream"
                )

                val done = ContentValues().apply {

                    put(
                        MediaStore.Downloads.IS_PENDING,
                        0
                    )
                }

                resolver.update(
                    uri,
                    done,
                    null,
                    null
                )

                activity.runOnUiThread {

                    android.widget.Toast.makeText(
                        activity,
                        "CSV saved: Downloads/Pathpedi/$safeName",
                        android.widget.Toast.LENGTH_LONG
                    ).show()
                }

                true

            } catch (e: Exception) {

                resolver.delete(
                    uri,
                    null,
                    null
                )

                throw e
            }

        } else {

            val downloads =
                Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOWNLOADS
                )

            val folder = File(
                downloads,
                "Pathpedi"
            )

            if (
                !folder.exists() &&
                !folder.mkdirs()
            ) {
                throw Exception(
                    "Could not create Downloads/Pathpedi"
                )
            }

            val file = File(
                folder,
                safeName
            )

            FileOutputStream(file).use {
                it.write(bytes)
            }

            activity.runOnUiThread {

                android.widget.Toast.makeText(
                    activity,
                    "CSV saved: Downloads/Pathpedi/$safeName",
                    android.widget.Toast.LENGTH_LONG
                ).show()
            }

            true
        }

    } catch (e: Exception) {

        e.printStackTrace()

        activity.runOnUiThread {

            android.widget.Toast.makeText(
                activity,
                "CSV save failed: " +
                    (e.message ?: "Unknown error"),
                android.widget.Toast.LENGTH_LONG
            ).show()
        }

        false
    }
}
@JavascriptInterface
fun saveBackup(filename: String, base64Data: String): Boolean {

    val activity = context as? MainActivity ?: return false

    return try {

        val safeName = filename
            .replace("/", "_")
            .replace("\\", "_")
            .ifBlank { "pathpedi_backup.json" }

        val bytes = Base64.decode(
            base64Data,
            Base64.DEFAULT
        )

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {

            val values = ContentValues().apply {

                put(
                    MediaStore.Downloads.DISPLAY_NAME,
                    safeName
                )

                put(
                    MediaStore.Downloads.MIME_TYPE,
                    "application/json"
                )

                put(
                    MediaStore.Downloads.RELATIVE_PATH,
                    Environment.DIRECTORY_DOWNLOADS + "/Pathpedi/"
                )

                put(
                    MediaStore.Downloads.IS_PENDING,
                    1
                )
            }

            val resolver = activity.contentResolver

            val uri = resolver.insert(
                MediaStore.Downloads.EXTERNAL_CONTENT_URI,
                values
            ) ?: throw Exception(
                "Backup MediaStore insert failed"
            )

            try {

                resolver.openOutputStream(uri)?.use { output ->

                    output.write(bytes)
                    output.flush()

                } ?: throw Exception(
                    "Could not open backup output stream"
                )

                val done = ContentValues().apply {

                    put(
                        MediaStore.Downloads.IS_PENDING,
                        0
                    )
                }

                resolver.update(
                    uri,
                    done,
                    null,
                    null
                )

                activity.runOnUiThread {

                    android.widget.Toast.makeText(
                        activity,
                        "Backup saved: Downloads/Pathpedi/$safeName",
                        android.widget.Toast.LENGTH_LONG
                    ).show()
                }

                true

            } catch (e: Exception) {

                resolver.delete(
                    uri,
                    null,
                    null
                )

                throw e
            }

        } else {

            val downloads =
                Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOWNLOADS
                )

            val folder = File(
                downloads,
                "Pathpedi"
            )

            if (
                !folder.exists() &&
                !folder.mkdirs()
            ) {
                throw Exception(
                    "Could not create Downloads/Pathpedi"
                )
            }

            val file = File(
                folder,
                safeName
            )

            FileOutputStream(file).use {
                it.write(bytes)
            }

            activity.runOnUiThread {

                android.widget.Toast.makeText(
                    activity,
                    "Backup saved: Downloads/Pathpedi/$safeName",
                    android.widget.Toast.LENGTH_LONG
                ).show()
            }

            true
        }

    } catch (e: Exception) {

        e.printStackTrace()

        activity.runOnUiThread {

            android.widget.Toast.makeText(
                activity,
                "Backup save failed: " +
                    (e.message ?: "Unknown error"),
                android.widget.Toast.LENGTH_LONG
            ).show()
        }

        false
    }
}
        private fun decodeJsString(value: String): String {
            if (
                value.length >= 2 &&
                value.first() == '"' &&
                value.last() == '"'
            ) {
                return try {
                    org.json.JSONTokener(value)
                        .nextValue()
                        .toString()
                } catch (e: Exception) {
                    value.substring(1, value.length - 1)
                }
            }
            return value
        }
    }
}
